### ISSUE TITLE
put some comments

### ISSUE THREAD

**Issue by Solimanmelay** [Solimanmelay/SOLIMAN-SABAS-DATO-ARMANDO_LAB3#3]
What: Put some comments
Where: At the Public Class Clock
When: Until 10pm
Who: Hazel Sabas
Why: just because

**Comment by SabasHazelAnn** [comment]
// Method to convert seconds to minutes
// Method to convert seconds to hours
// Method to convert minutes to seconds
// Method to convert minutes to hours
// Method to convert hours to seconds
// Method to convert hours to minutes 
// Display menu and handle user's choice
// Loop to keep asking for conversions until the user decides to exit
// Displaying the conversion menu
// Get user's choice
// Convert seconds to minutes
// Convert seconds to hours
// Convert minutes to seconds
// Convert minutes to hours
// Convert hours to seconds
// Convert hours to minutes
// Invalid choice
// Ask if the user wants to perform another conversion
// Check if the user wants to continue or exit 
// Close the scanner

**Comment by SabasHazelAnn** [comment]
finished and posted comments

**Comment by SabasHazelAnn** [comment]
I'm done

**Comment by SabasHazelAnn** [comment]
done
